# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

#        in_memory:
 #           memory:
  #              users:
   #                 sash:
    #                  password: $2y$12$Jw9SWl3Y2Sk6UGsTDCprtOfZft5BXHaYyw4w4.fFcR.jSb.ThIWiG
     #                 roles: 'ROLE_ADMIN'
                   # krial:
                    #  password: $2y$12$Jw9SWl3Y2Sk6UGsTDCprtOfZft5BXHaYyw4w4.fFcR.jSb.ThIWiG
                     # roles: 'ROLE_USER'

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

#    encoders:
 #       Symfony\Component\Security\Core\User\User:
  #          algorithm: bcrypt
   #         cost: 12
            # bin/console security:encode-password

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #secured_area:
        #            logout:
        #                path:   /logout
        #                target: /

        main:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider   # for db
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/article, roles: ROLE_ADMIN }